PR - Issue 568 typecast fix for 1D array or list
authorjapps/zerocode pull request #577
Opened 2023-05-31 15:47 UTC by nirmalchandra

# <Feature Title>

PR Branch
**_#ADD LINK TO THE PR BRANCH_**

## Motivation and Context

## Checklist:

* [x] Unit tests added

* [x] Integration tests added

* [x] Test names are meaningful

* [x] Feature manually tested

* [x] Branch build passed

* [x] No 'package.*' in the imports

* [ ] Relevant Wiki page updated with clear instruction for the end user
  * [x] Not applicable. This was only a refactor change, no functional or behaviour changes were introduced

* [ ] Http test added to `http-testing` module(if applicable) ?
  * [x] Not applicable. The changes did not affect HTTP automation flow

* [ ] Kafka test added to `kafka-testing` module(if applicable) ?
  * [x] Not applicable. The changes did not affect Kafka automation flow

2023-05-31 16:22 UTC, authorjapps approved these changes

2023-06-05 13:07 UTC, M3lkior requested changes

2023-06-05 13:07 UTC, M3lkior commented on core/src/main/java/org/jsmart/zerocode/core/utils/FieldTypeConversionUtils.java
>              LOGGER.error(errorMsg + "\nException Details:" + exx);
```suggestion
            LOGGER.error("{} with exception details: {}",  errorMsg, exx);
```

2023-06-05 13:07 UTC, M3lkior commented on core/src/test/java/org/jsmart/zerocode/core/utils/FieldTypeConversionUtilsTest.java
> +        assertEquals(2, jsonNode.get("ids").get(1).asInt());
int or float ? ;)

2023-06-05 15:57 UTC, authorjapps commented on core/src/test/java/org/jsmart/zerocode/core/utils/FieldTypeConversionUtilsTest.java
> +        assertEquals(2, jsonNode.get("ids").get(1).asInt());
Fixed

2023-06-05 16:00 UTC, M3lkior requested changes

2023-06-05 16:33 UTC, authorjapps commented
Thanks for reviewing @M3lkior.
Both review comments have been fixed.
Will be merging the PR and releasing soon.
ETA: 11/June

2023-06-05 16:34 UTC, merged